### ISSUE TITLE
Count Column not showing up on asset indexes

### ISSUE THREAD

**Issue by klick** [engram-design/AssetCount#1]
The count works fine, the column is not showing up though. Possible version conflict?
Running Craft 2.6.2949

**Comment by engram-design** [comment]
Hard to say, but there was a config setting `showCountOnAssetIndex`  that was off by default. As of [1.0.0](https://github.com/verbb/asset-count/releases/tag/1.0.0) for Craft 3, this is on by default.

Also sorry for missing this comment for years!!

**Comment by RobbeReygel** [comment]
This problem seems to be recurring in the latest release.

I can retrieve the count in frontend using craft.assetCount.getCount(file.id) but it doesn't appear to be shown anywhere in the CMS.

**Comment by engram-design** [comment]
@RobbeReygel What version of the plugin and Craft are you on? For either instance, there's a "View Count" column that you can select. It won't appear automatically. This issue is pretty old (from Craft 2 and early Craft 3 days) before the concept of custom element index columns, which would've been the reason for the `showCountOnAssetIndex` config setting

![CleanShot 2022-05-13 at 16 07 02](https://user-images.githubusercontent.com/1221575/168221480-4e43dec9-2f89-4328-a07b-0e91c044340a.png)
